default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: gift_confirmer_development

test:
  <<: *default
  database: gift_confirmer_test

production:
  <<: *default
  database: gift_confirmer_production
  username: gift_confirmer
  password: <%= ENV["GIFT_CONFIRMER_DATABASE_PASSWORD"] %>
